#!/usr/bin/expect -f

set network ""

if {[llength $argv] == 0} {
	set network [exec nmcli connection show | grep vpn | awk {NR==1{print $1}}]
} else {
	set network [lindex $argv 0]
}

set uuid [exec nmcli connection show | grep $network | awk {NR==1{print $2}}]

set pass [exec secret-tool lookup setting-name vpn connection-uuid "$uuid"]

spawn nmcli connection up --ask "$network"

expect {
	"Password (vpn.secrets.password):" { send "$pass\r"; exp_continue}
	"•" {exp_continue}
	eof
}
